VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Client"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True

Private Sub ReBoot(Equipment As Winsock, RemoteHostName As String, Port As Integer, Array_Bool As Boolean, Index As Integer)
With Equipment
    .Close
    .Connect RemoteHostName, Port
End With
End Sub

